# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: eit-uks-prd-win-ado-agent-pool

steps:
- script: |
    wmic diskdrive get size
    systeminfo
  displayName: 'Run a one-line script'
