# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: eit-uks-prd-win-ado-agent-pool


steps:
    - script: |
        wmic diskdrive get size
        systeminfo
      displayName: 'Run a one-line script'
      
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
            $tempPath = "%%TEMP%%"

            # Get all files in the TEMP directory
            $files = Get-ChildItem -Path $tempPath -File
            
            # Display the file names
            foreach ($file in $files) {
                Write-Host $file.FullName
            }
