# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: eit-uks-prd-win-ado-agent-pool


steps:
    - script: |
        wmic diskdrive get size
        systeminfo
      displayName: 'Run a one-line script'
      
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
            $folders = @("$env:TEMP\M365Management\FileCache", "$env:TEMP\tmpEXO*")
            while ($true) {
                foreach ($folder in $folders) {
                    $files = Get-ChildItem -Path $folder -Recurse -ErrorAction SilentlyContinue
                    if ($files) {
                        $size = ($files | Measure-Object Length -Sum).Sum / 1MB
                        $fileCount = $files.Count
                        Write-Host "Folder: $folder"
                        Write-Host "File count: $fileCount"
                        Write-Host "Total size: $([math]::Round($size, 2)) MB"
                        Write-Host ""
                    } else {
                        Write-Host "Folder: $folder not found or no files."
                    }
                }
            }
